### PR TITLE
feat: add routes API (#11)

### LINKED ISSUE #11: Add API routes
The user should be able to add routes to `pages/api` that should be treated as server side API endpoints rather than HTML pages. The signature for an API route would look something like this:

```ts
// pages/api/redirect.ts

export default async (req: Request): Promise<Response> => {
  return Response.redirect(req.headers.get("X-Redirect-To"), 307); 
}
```

### PR DESCRIPTION
**Pull request by RoXuS**
Hey!

Can I have some feedback about this attemp to fix #11?

It would be great for us to read some files from the server or call some API from the backend.

Thx for your framework.

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
Thanks @RoXuS for the PR. This is not quite how I want to implement this feature. I will need to do some more preparatory work before this can be done.

**Comment by RoXuS** [comment]
ok :)

**Comment by aadamsx** [comment]
Will not use this framework unless/until I can build server side route, why has this feature taken so long?  Is there a technical holdup?

**Comment by lucacasonato** [comment]
> Will not use this framework unless/until I can build server side routes, why has this feature taken so long? Is there a technical holdup?

Well that sucks for you I guess... don't ever "expect" something from an open source project unless you pay for it or actively contribute to it. You are not paying for this project, nor are you contributing. If you want to sponsor me to implement this, feel free: https://github.com/sponsors/lucacasonato. It is not a feature I require at the moment, so I have not spent time to implement it.

**Comment by aadamsx** [comment]
> It is not a feature I require at the moment, so I have not spent time to implement it.

You don't need the feature and therefore not working on it (I get that), but holding up PRs to implement it - not a great situation.   

So no, I won't be using this over Alephjs https://alephjs.org/ or even rolling my own solution once preact gets things in order with respect to Deno.

Good luck

**Pull request closed without merging**
