### PR TITLE
feat: add sourcemap and minify options

### PR DESCRIPTION
**Pull request by kt3k**
This PR adds `sourcemap` and `minify` option for `build` command. This reduces the build time of `dext build` when these are disabled.

When I measured the effect of these options with example directory, it reduced 23% build time on my machine ( 7.400s -> 5.680s ) (measured with `build --typecheck=false`.)

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
LGTM

**Comment by lucacasonato** [comment]
Can you rebase the PR with main?

**Comment by kt3k** [comment]
done!

**Comment by lucacasonato** [comment]
Thanks :-)

**Pull request merged**
